openapi: 3.0.1
info:
  title: GitHub API
  description: ''
  version: '1.0'
servers:
  - url: https://apim-demo-integrationsvcs.azure-api.net/gh
paths:
  /:
    get:
      summary: Get Authed User
      description: Get Authed User
      operationId: list-gists-for-authed-user
      parameters:
        - name: since
          in: query
          schema:
            type: ''
        - name: per_page
          in: query
          schema:
            enum:
              - ''
            type: ''
        - name: page
          in: query
          schema:
            enum:
              - ''
            type: ''
        - name: Accept
          in: header
          schema:
            enum:
              - ''
            type: ''
        - name: Authorization
          in: header
          schema:
            type: ''
      responses:
        '200':
          description: ''
        '304':
          description: ''
        '401':
          description: ''
        '403':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]